name: .NET

on:
  push:
    branches: [ pre-release ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TF_BUILD: true
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish NuGet
      # You may pin to the exact commit or the version.
      # uses: brandedoutcast/publish-nuget@c12b8546b67672ee38ac87bea491ac94a587f7cc
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: Open.PackML/Open.PackML.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          VERSION_FILE_PATH: common.props
          INCLUDE_SYMBOLS: true
          NO_BUILD: true
